language: python
sudo: required
services:
  - docker

python:
  - "2.7"
  - "3.4"
  - "3.5"

before_install:
  # kubectl
  - sudo apt-get install curl -y
  - curl -O https://storage.googleapis.com/kubernetes-release/release/v1.3.4/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/kubectl

  - sudo make requirements

install:
  - sudo make install

before_script:
  - sudo make syntax-check

script:
  # run tests
  - make test
  - make integration-test

after_success:
  - sudo coveralls
